export const currencyData = [
  "MNT - Mongolian Tugrik",
  "USD - United States Dollar",
  "EUR - Euro",
  "GBP - British Pound Sterling",
  "JPY - Japanese Yen",
  "AUD - Australian Dollar",
  "CAD - Canadian Dollar",
  "CHF - Swiss Franc",
  "CNY - Chinese Yuan",
  "SEK - Swedish Krona",
  "NZD - New Zealand Dollar",
  "INR - Indian Rupee",
  "BRL - Brazilian Real",
  "RUB - Russian Ruble",
  "ZAR - South African Rand",
  "MXN - Mexican Peso",
  "SGD - Singapore Dollar",
  "HKD - Hong Kong Dollar",
  "NOK - Norwegian Krone",
  "DKK - Danish Krone",
  "TRY - Turkish Lira",
  "KRW - South Korean Won",
  "AED - United Arab Emirates Dirham",
  "SAR - Saudi Riyal",
  "THB - Thai Baht",
  "IDR - Indonesian Rupiah",
  "MYR - Malaysian Ringgit",
  "PHP - Philippine Peso",
  "HUF - Hungarian Forint",
  "PLN - Polish Złoty",
  "CZK - Czech Koruna",
  "ILS - Israeli New Shekel",
  "CLP - Chilean Peso",
  "ARS - Argentine Peso",
  "EGP - Egyptian Pound",
  "NGN - Nigerian Naira",
];
